language: java
matrix:
    include:
        - os: linux
          jdk: oraclejdk8
        - os: linux
          jdk: openjdk8
        - os: osx
          osx_image: xcode9.1
before_install:
 - date -u
 - uname -a
 - env | sort
branches:
 only:
   - master
notifications:
 email:
  - support@openam.org.ru
cache:
  directories:
  - $HOME/.m2
before_script:
  - git submodule foreach git checkout master
  - git submodule foreach git checkout master
script:
  - mvn -q clean install
